const esc = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
const route = (path, label, icon = '') => `<a class="nav-item" href="#${path}" data-route="${path}"><span>${icon}</span> ${label}</a>`;
const button = (label, path = '', kind = 'button-secondary') => path ? `<a class="button ${kind}" href="#${path}" data-route="${path}">${label}</a>` : `<button class="button ${kind}" type="button" data-prototype-action>${label}</button>`;
const initials = (name = 'C') => esc(name.slice(0, 1).toUpperCase());
const badge = (text, tone = '') => `<span class="status-badge ${tone ? `status-${tone}` : ''}">${esc(text)}</span>`;
const alertBox = (message = '') => message ? `<div class="prototype-alert">${esc(message)}</div>` : '';

function sidebar(state) {
  const publicMode = state.mode !== 'user';
  return `<aside class="sidebar" aria-label="Navegação principal">
    <a class="brand brand-sidebar" href="#${publicMode ? '/explorar' : '/dashboard'}" data-route="${publicMode ? '/explorar' : '/dashboard'}"><span class="brand-mark">C</span><span>cypher</span></a>
    <div class="sidebar-profile"><div class="avatar avatar-small">${initials(publicMode ? state.mode === 'ghost' ? 'G' : 'C' : state.user.artistico)}</div><div><strong>${esc(publicMode ? state.mode === 'ghost' ? 'Visitante' : 'Protótipo' : state.user.artistico)}</strong><span>${state.mode === 'ghost' ? 'Modo Fantasma' : publicMode ? 'Acesso público' : `@${esc(state.user.username)}`}</span></div></div>
    <nav class="nav-list">${publicMode ? `${route('/explorar', 'Explorar', '⌂')}${route('/beats', 'Beats', '◉')}${route('/eventos', 'Eventos', '◷')}${route('/conhecimento', 'Conhecimento', '?')}` : `${route('/dashboard', 'Dashboard', '⌂')}${route('/perfil', 'Meu perfil', '○')}${route('/portfolio', 'Portfólio', '▤')}${route('/obras', 'Minhas obras', '♫')}${route('/beats', 'Banco de beats', '◉')}${route('/eventos', 'Eventos', '◷')}${route('/colaboracao', 'Colaboração', '◎')}${route('/conhecimento', 'Conhecimento', '?')}`}</nav>
    <div class="sidebar-bottom"><button class="theme-toggle" type="button" data-theme-toggle><span data-theme-icon>◐</span><span data-theme-label>Tema escuro</span></button>${state.mode === 'ghost' ? `<a class="sidebar-cta" href="#/login" data-route="/login">Criar minha conta <span>↗</span></a>` : publicMode ? `<a class="sidebar-cta" href="#/login" data-route="/login">Entrar no Cypher <span>↗</span></a>` : `<button class="nav-item logout" type="button" data-logout><span>↪</span> Sair</button>`}</div>
  </aside>
  <nav class="mobile-nav" aria-label="Navegação móvel"><a class="mobile-nav-item" href="#${publicMode ? '/explorar' : '/dashboard'}" data-route="${publicMode ? '/explorar' : '/dashboard'}"><span>⌂</span><small>Início</small></a><a class="mobile-nav-item" href="#${publicMode ? '/beats' : '/obras'}" data-route="${publicMode ? '/beats' : '/obras'}"><span>♫</span><small>${publicMode ? 'Beats' : 'Obras'}</small></a><a class="mobile-nav-item" href="#/eventos" data-route="/eventos"><span>◷</span><small>Eventos</small></a><a class="mobile-nav-item" href="#${publicMode ? '/login' : '/perfil'}" data-route="${publicMode ? '/login' : '/perfil'}"><span>○</span><small>${publicMode ? 'Entrar' : 'Perfil'}</small></a></nav>`;
}

function shell(state, title, body, options = {}) {
  const auth = options.auth === true;
  return auth ? `<main class="auth-layout"><section class="auth-intro"><a class="brand brand-large" href="#/login" data-route="/login"><span class="brand-mark">C</span><span>cypher</span></a><div class="intro-copy"><p class="eyebrow">A cena é feita de conexões</p><h1>Um espaço para<br><em>criar junto.</em></h1><p>Mostre seu trabalho, encontre parceiros e transforme colaboração em trajetória.</p></div><div class="register-points"><span>01 <strong>Perfil com propósito</strong></span><span>02 <strong>Obras e créditos organizados</strong></span><span>03 <strong>Conexões que fazem sentido</strong></span></div></section>${body}</main>` : `<div class="app-shell">${sidebar(state)}<main class="content"><header class="page-header page-header-line"><div><p class="eyebrow">Cypher / protótipo</p><h1>${title}</h1></div><div class="header-actions">${state.mode === 'user' ? `<span class="prototype-user">${esc(state.user.artistico)} <small>protótipo</small></span>` : ''}</div></header>${body}</main></div>`;
}

export function loginView(message = '') {
  return `<main class="auth-layout auth-layout-login"><section class="auth-intro login-intro"><a class="brand brand-large" href="#/login" data-route="/login"><span class="brand-mark">C</span><span>cypher</span></a><div class="intro-copy"><p class="eyebrow">A cena é feita de conexões</p><h1>Um espaço para<br><em>criar junto.</em></h1><p>Artistas, beatmakers, produtores e DJs conectados por um mesmo propósito.</p></div><div class="intro-quote">“O som fica maior quando a gente cria em conjunto.”<small>— Manifesto Cypher</small></div></section><section class="auth-card-wrap"><div class="auth-card"><div class="mobile-brand"><a class="brand" href="#/login" data-route="/login"><span class="brand-mark">C</span><span>cypher</span></a></div><p class="eyebrow">Bem-vindo de volta</p><h2>Entrar no Cypher</h2><p class="muted">Acesse seu espaço de criação e colaboração.</p>${alertBox(message)}<form class="form-stack" data-login-form><label for="login">E-mail ou username</label><input id="login" name="login" placeholder="lianoise ou cypher@demo.com" autocomplete="username" required><label for="password">Senha</label><input id="password" name="password" type="password" placeholder="••••••••" autocomplete="current-password" required><div class="demo-hint"><strong>Conta de demonstração</strong><span>lianoise · cypher123</span></div><button class="button button-primary button-full" type="submit">Entrar no Cypher <span>↗</span></button></form><div class="auth-divider"><span>ou</span></div><button class="ghost-button" type="button" data-ghost-login><span>◌</span><div><strong>Explorar em Modo Fantasma</strong><small>Veja o ecossistema sem criar uma conta</small></div><span>→</span></button><p class="auth-footer">Ainda não tem uma conta? <a href="#/cadastro" data-route="/cadastro">Conheça o protótipo</a></p></div></section></main>`;
}

export function exploreView(state) {
  const action = state.mode === 'user' ? button('Abrir meu dashboard ↗', '/dashboard', 'button-primary') : button('Entrar no Cypher ↗', '/login', 'button-primary');
  return shell(state, 'Encontre seu próximo movimento.', `<div class="prototype-banner"><span>◌</span><div><strong>${state.mode === 'ghost' ? 'Você está no Modo Fantasma.' : 'Você está explorando o protótipo.'}</strong><p>As telas estão navegáveis para demonstração. As ações de publicação e colaboração são apenas visuais.</p></div>${state.mode === 'ghost' ? button('Criar conta', '/login', 'button-secondary') : ''}</div><section class="explore-hero"><div><p class="eyebrow">A rede está viva</p><h2>Seu próximo som<br>pode começar <em>aqui.</em></h2><p>Descubra profissionais, beats, encontros e oportunidades que fazem sentido para sua trajetória.</p><div class="hero-actions">${action}</div></div><div class="hero-art"><span class="hero-art-circle"></span><strong>C</strong><small>CONNECT<br>CREATE<br>COLLAB</small></div></section><section class="section-heading section-heading-first"><div><p class="eyebrow">Agora na comunidade</p><h2>O que está acontecendo</h2></div></section><div class="quick-grid"><a class="quick-card card" href="#/beats" data-route="/beats"><span class="quick-icon">◉</span><div><strong>Banco de beats</strong><p>Instrumentais para sua próxima obra.</p></div><span>↗</span></a><a class="quick-card card" href="#/eventos" data-route="/eventos"><span class="quick-icon quick-icon-gold">◷</span><div><strong>Eventos e oportunidades</strong><p>Encontros e chamadas abertas.</p></div><span>↗</span></a><a class="quick-card card" href="#/colaboracao" data-route="/colaboracao"><span class="quick-icon quick-icon-dark">◎</span><div><strong>Colaboração</strong><p>Profissionais para criar junto.</p></div><span>↗</span></a></div>`);
}

export function dashboardView(state) {
  return shell(state, `Bom te ver, <em>${esc(state.user.artistico)}.</em>`, `<div class="prototype-banner"><span>✦</span><div><strong>Protótipo frontend ativo.</strong><p>Os cards abaixo representam o ecossistema completo. Formulários e botões de cadastro estão desativados nesta demonstração.</p></div></div><section class="dashboard-grid"><div class="dashboard-main"><div class="section-heading section-heading-first"><div><p class="eyebrow">Resumo do seu espaço</p><h2>Continue criando.</h2></div><span class="date-label">HOJE · 16 SET 2026</span></div><div class="stats-grid"><div class="stat-card card"><span>Obras autorais</span><strong>${state.obras.length}</strong><small>+2 neste mês</small></div><div class="stat-card card"><span>Conexões</span><strong>12</strong><small>+4 aguardando</small></div><div class="stat-card card"><span>Visualizações</span><strong>284</strong><small>últimos 30 dias</small></div></div><div class="section-heading"><div><p class="eyebrow">Seu catálogo</p><h2>Obras recentes</h2></div><a class="text-link" href="#/obras" data-route="/obras">Ver todas <span>→</span></a></div><div class="work-list card">${state.obras.slice(0, 3).map((obra) => `<a class="work-row" href="#/obras" data-route="/obras"><div class="work-thumb">${esc(obra.capa)}</div><div class="work-info"><strong>${esc(obra.titulo)}</strong><small>${esc(obra.tipo)} · ${esc(obra.genero)}</small></div>${badge(obra.status, obra.status === 'Lançada' ? 'published' : '')}<span class="row-arrow">→</span></a>`).join('')}</div></div><aside class="dashboard-aside"><div class="profile-mini card"><div class="avatar avatar-profile">${initials(state.user.artistico)}</div><p class="eyebrow">Seu perfil</p><h3>${esc(state.user.artistico)}</h3><p>@${esc(state.user.username)} · ${esc(state.user.cidade)}</p><a href="#/perfil" data-route="/perfil" class="text-link">Ver perfil <span>↗</span></a></div><div class="aside-note card"><span>✦</span><strong>Seu espaço, suas regras.</strong><p>Compartilhe apenas o que estiver pronto. O Modo Fantasma continua disponível para explorar.</p></div></aside></section>`);
}

export function profileView(state, editing = false) {
  if (editing) return shell(state, 'Editar <em>perfil.</em>', `<div class="back-link" data-route="/perfil">← Voltar para meu perfil</div><div class="editor-card card"><div class="form-section"><div class="form-section-title"><span>01</span><div><h2>Identidade profissional</h2><p>Campos demonstrativos, sem salvamento real.</p></div></div><form class="form-stack" data-prototype-form><label>Nome artístico</label><input value="${esc(state.user.artistico)}"><label>Username</label><input value="${esc(state.user.username)}"><label>Biografia</label><textarea rows="6">${esc(state.user.bio)}</textarea><label>Categorias</label><div class="category-grid">${state.user.categorias.map((c) => `<label class="check-card"><input type="checkbox" checked><span>${esc(c)}</span></label>`).join('')}</div><div class="editor-actions"><a href="#/perfil" class="button button-quiet" data-route="/perfil">Cancelar</a><button class="button button-primary" type="submit">Salvar alterações ↗</button></div></form></div></div>`);
  return shell(state, 'Meu <em>perfil.</em>', `<div class="profile-hero card"><div class="avatar avatar-profile">${initials(state.user.artistico)}</div><div><p class="eyebrow">Perfil profissional</p><h2>${esc(state.user.artistico)}</h2><p>@${esc(state.user.username)} · ${esc(state.user.cidade)}, ${esc(state.user.estado)}</p><p class="profile-bio">${esc(state.user.bio)}</p><div class="tag-list">${state.user.categorias.map((c) => `<span>${esc(c)}</span>`).join('')}</div></div><a href="#/perfil/editar" data-route="/perfil/editar" class="button button-secondary">Editar perfil ↗</a></div><div class="profile-columns"><section><div class="section-heading section-heading-first"><div><p class="eyebrow">Presença na rede</p><h2>Sobre o trabalho</h2></div></div><div class="profile-info-grid"><div class="card info-card"><span>Localização</span><strong>${esc(state.user.cidade)}, ${esc(state.user.estado)}</strong></div><div class="card info-card"><span>Reputação</span><strong>4.8 <small>★ · 6 avaliações</small></strong></div><div class="card info-card"><span>Conexões</span><strong>12 profissionais</strong></div></div></section><aside class="profile-social card"><p class="eyebrow">Links profissionais</p><a href="#" data-prototype-action>instagram.com/lianoise <span>↗</span></a><a href="#" data-prototype-action>soundcloud.com/lianoise <span>↗</span></a><a href="#" data-prototype-action>youtube.com/@lianoise <span>↗</span></a></aside></div>`);
}

export function portfolioView(state) {
  return shell(state, 'Meu <em>portfólio.</em>', `<section class="portfolio-hero card"><div class="avatar avatar-profile">${initials(state.user.artistico)}</div><div><p class="eyebrow">Portfólio de</p><h2>${esc(state.user.artistico)}</h2><p>@${esc(state.user.username)} · ${esc(state.user.cidade)}, ${esc(state.user.estado)}</p><p class="portfolio-bio">${esc(state.user.bio)}</p></div><div class="portfolio-counts"><strong>${state.obras.length}</strong><span>obras autorais</span><strong>${state.creditos.length}</strong><span>colaborações</span></div></section><div class="section-heading section-heading-first"><div><p class="eyebrow">Modo inteligente</p><h2>Obras autorais</h2></div><a href="#/obras" data-route="/obras" class="text-link">Ver catálogo <span>→</span></a></div><section class="portfolio-works-grid">${state.obras.map((obra) => `<article class="portfolio-work card"><div class="portfolio-work-art"><span>♫</span></div><div><h3>${esc(obra.titulo)}</h3><p>${esc(obra.genero)} · ${obra.bpm} BPM</p>${badge(obra.status, obra.status === 'Lançada' ? 'published' : '')}</div></article>`).join('')}</section><div class="section-heading section-heading-spaced"><div><p class="eyebrow">Histórico de colaboração</p><h2>Participações</h2></div></div><section class="portfolio-credit-list card">${state.creditos.map((credito) => `<div class="portfolio-credit-row"><div class="quick-icon">◎</div><div><strong>${esc(credito.obra)}</strong><small>${esc(credito.funcao)}</small></div>${badge(credito.status, credito.status === 'Lançada' ? 'published' : '')}<button class="button button-secondary button-small" data-prototype-action>Avaliar participação</button></div>`).join('')}</section>`);
}

export function worksView(state) {
  return shell(state, 'Minhas <em>obras.</em>', `<div class="prototype-banner"><span>◈</span><div><strong>Catálogo visual de demonstração.</strong><p>O cadastro, edição e exclusão de obras estão propositalmente desativados nesta versão frontend.</p></div>${button('Cadastrar obra', '/obras/cadastro', 'button-primary')}</div><div class="section-heading section-heading-first"><div><p class="eyebrow">Seu catálogo</p><h2>${state.obras.length} obras no espaço</h2></div><div class="filter-chips"><span class="filter-chip active">Todas</span><span class="filter-chip">Lançadas</span><span class="filter-chip">Rascunhos</span></div></div><section class="works-masonry">${state.obras.map((obra) => `<article class="work-large-card card"><div class="work-large-art"><span>${esc(obra.capa)}</span><small>${esc(obra.tipo)}</small></div><div class="work-large-info"><div><h2>${esc(obra.titulo)}</h2><p>${esc(obra.genero)} · ${obra.bpm} BPM</p></div>${badge(obra.status, obra.status === 'Lançada' ? 'published' : '')}</div><div class="work-large-footer"><span>Atualizado em ${esc(obra.data)}</span><button type="button" data-prototype-action>•••</button></div></article>`).join('')}</section>`);
}

export function beatsView(state) {
  return shell(state, 'Banco de <em>beats.</em>', `<div class="prototype-banner"><span>◉</span><div><strong>Encontre o instrumental da próxima obra.</strong><p>O catálogo abaixo é demonstrativo. Player, publicação e compra não possuem operação real.</p></div>${state.mode === 'user' ? button('Publicar beat', '/beats/cadastro', 'button-primary') : button('Entrar para publicar', '/login', 'button-primary')}</div><section class="beat-toolbar card"><form class="beat-search" data-filter-form><input name="search" placeholder="Pesquisar por título, gênero ou profissional..."><button class="button button-secondary" type="submit">Buscar ⌕</button></form><div class="beat-filters"><span class="filter-chip active">Todos</span><span class="filter-chip">Disponíveis</span><span class="filter-chip">Free use</span></div></section><section class="section-heading section-heading-first"><div><p class="eyebrow">Amostras públicas</p><h2>Beats recentes</h2></div><span class="results-count">${state.beats.length} resultados</span></section><section class="beats-grid">${state.beats.map((beat) => `<article class="beat-card card"><div class="beat-cover"><span class="work-art-lines"></span><strong>◉</strong><small>${beat.bpm} BPM</small></div><div class="beat-body"><div class="beat-title-row"><div><h2>${esc(beat.titulo)}</h2><p>${esc(beat.autor)} · ${esc(beat.handle)}</p></div><span class="availability-badge">${esc(beat.status)}</span></div><div class="beat-meta"><span>${esc(beat.genero)}</span><span>${esc(beat.tom)}</span></div><p class="beat-description">${esc(beat.descricao)}</p><button class="demo-audio-button" data-demo-player>▶ Ouvir demonstração</button></div></article>`).join('')}</section>`);
}

export function eventsView(state) {
  return shell(state, 'Eventos e <em>oportunidades.</em>', `<div class="prototype-banner"><span>◷</span><div><strong>Movimento da cena.</strong><p>Encontre encontros, chamadas e espaços para fazer sua trajetória acontecer.</p></div>${state.mode === 'user' ? button('Criar evento', '/eventos/cadastro', 'button-primary') : button('Criar conta', '/login', 'button-primary')}</div><div class="section-heading section-heading-first"><div><p class="eyebrow">Agenda</p><h2>Próximos eventos</h2></div><span class="results-count">${state.eventos.length} eventos</span></div><section class="events-grid">${state.eventos.map((event) => `<article class="event-card card"><div class="event-date"><strong>${event.dia}</strong><span>${event.mes}</span></div><div class="event-content"><div class="event-label">${esc(event.categoria)}</div><h3>${esc(event.titulo)}</h3><p>${esc(event.descricao)}</p><div class="event-meta"><span>◷ ${event.horario}</span><span>⌖ ${esc(event.local)} · ${esc(event.cidade)}</span></div><small class="event-organizer">Por <strong>${esc(event.organizador)}</strong> · ${event.interessados} interessados</small></div><button class="button button-secondary button-small" data-prototype-action>Tenho interesse ↗</button></article>`).join('')}</section><div class="section-heading section-heading-spaced"><div><p class="eyebrow">Chamadas abertas</p><h2>Oportunidades</h2></div><span class="results-count">${state.oportunidades.length} oportunidades</span></div><section class="opportunities-grid">${state.oportunidades.map((op) => `<article class="opportunity-card card"><div class="opportunity-icon">✳</div><div class="opportunity-content"><div class="event-label">${esc(op.tipo)}</div><h3>${esc(op.titulo)}</h3><p>${esc(op.descricao)}</p><div class="event-meta"><span>⌖ ${esc(op.local)}</span><span>${esc(op.prazo)}</span></div><small class="event-organizer">Por <strong>${esc(op.autor)}</strong> · ${op.candidaturas} candidaturas</small></div><button class="button button-primary button-small" data-prototype-action>Candidatar-se ↗</button></article>`).join('')}</section>`);
}

export function collaborationView(state) {
  return shell(state, 'Colabore com a <em>cena.</em>', `<div class="prototype-banner"><span>◎</span><div><strong>Rede profissional demonstrativa.</strong><p>A pesquisa e os estados de conexão estão disponíveis visualmente; nenhuma solicitação é gravada.</p></div></div><section class="collab-search card"><form class="beat-search" data-filter-form><input name="search" placeholder="Pesquisar por nome artístico, username ou nome..."><button class="button button-primary" type="submit">Pesquisar ⌕</button></form></section><div class="section-heading section-heading-first"><div><p class="eyebrow">Profissionais</p><h2>Encontre colaboradores</h2></div><span class="results-count">${state.profissionais.length} resultados</span></div><section class="professionals-grid">${state.profissionais.map((person) => { const link = state.conexoes.find((item) => item.id === person.id); return `<article class="professional-card card"><div class="avatar avatar-large">${esc(person.inicial)}</div><div class="professional-card-body"><h3>${esc(person.nome)}</h3><p>${esc(person.handle)} · ${esc(person.categoria)}</p>${link ? `<span class="connection-pill ${link.status !== 'Conectado' ? 'connection-pill-muted' : ''}">${esc(link.status)}</span>` : `<button class="button button-secondary button-small" data-prototype-action>Conectar +</button>`}</div></article>`; }).join('')}</section><div class="section-heading section-heading-spaced"><div><p class="eyebrow">Minha rede</p><h2>Conexões e solicitações</h2></div></div><section class="connection-list card">${state.conexoes.map((person) => `<div class="connection-row"><div class="avatar avatar-small">${esc(person.inicial)}</div><div class="connection-person"><strong>${esc(person.nome)}</strong><small>${esc(person.handle)}</small></div><span class="connection-pill ${person.status !== 'Conectado' ? 'connection-pill-muted' : ''}">${esc(person.status)}</span><button class="button button-quiet button-small" data-prototype-action>Gerenciar</button></div>`).join('')}</section>`);
}

export function knowledgeView(state) {
  return shell(state, 'Área de <em>conhecimento.</em>', `<div class="knowledge-intro"><p class="eyebrow">Aprender também é criar</p><p>Conteúdos rápidos para ajudar você a organizar sua trajetória profissional na música.</p></div><section class="knowledge-grid">${state.conhecimento.map((article, index) => `<article class="knowledge-card card"><div class="knowledge-number">0${index + 1}</div><div class="event-label">${esc(article.categoria)}</div><h2>${esc(article.titulo)}</h2><p>${esc(article.texto)}</p><button class="text-link" data-prototype-action>Continuar lendo <span>→</span></button></article>`).join('')}</section><div class="knowledge-tip"><span>i</span><p>Conteúdo estático para demonstração do protótipo. A área de administração de artigos não está conectada a um banco.</p></div>`);
}

export function formView(state, type) {
  const config = { cadastro: ['Criar seu <em>perfil.</em>', 'Primeiro passo', ['Nome completo', 'Nome artístico', 'Username', 'E-mail', 'Categorias', 'Senha', 'Confirmar senha']], obra: ['Cadastrar uma <em>obra.</em>', 'Obra musical', ['Título da obra', 'Gênero', 'BPM', 'Tipo de lançamento', 'Status']], beat: ['Publicar <em>beat.</em>', 'Instrumental', ['Título do beat', 'Gênero', 'BPM', 'Tom', 'Disponibilidade']], evento: ['Criar <em>evento.</em>', 'Nova atividade', ['Título do evento', 'Categoria', 'Data e horário', 'Local', 'Cidade']], oportunidade: ['Publicar <em>oportunidade.</em>', 'Nova chamada', ['Título', 'Tipo', 'Descrição', 'Data limite', 'Cidade']], perfil: ['Editar <em>perfil.</em>', 'Identidade profissional', ['Nome artístico', 'Username', 'Biografia', 'Categorias']] }[type] || ['Próxima <em>etapa.</em>', 'Demonstração', ['Campo demonstrativo']];
  return shell(state, config[0], `<div class="prototype-banner"><span>ⓘ</span><div><strong>Somente demonstração visual.</strong><p>Este formulário existe para apresentar o fluxo, mas não envia, salva ou altera dados.</p></div></div><div class="editor-card card"><div class="form-section-title"><span>01</span><div><h2>${config[1]}</h2><p>Preencha os campos para visualizar a interface.</p></div></div><form class="form-stack" data-prototype-form>${config[2].map((label, index) => `<label for="field-${index}">${label} ${index === 0 ? '<span class="required">*</span>' : ''}</label>${label === 'Descrição' || label === 'Biografia' ? `<textarea id="field-${index}" rows="6" placeholder="Escreva aqui..."></textarea>` : label === 'Categorias' ? `<div class="category-grid">${state.categorias.slice(0, 5).map((category) => `<label class="check-card"><input type="checkbox"><span>${esc(category)}</span></label>`).join('')}</div>` : `<input id="field-${index}" type="${label.includes('Senha') ? 'password' : label === 'E-mail' ? 'email' : label.includes('Data') ? 'datetime-local' : label === 'BPM' ? 'number' : 'text'}" placeholder="${label} demonstrativo">`}`).join('')}<div class="editor-actions"><button type="button" class="button button-quiet" data-route-back>Cancelar</button><button type="submit" class="button button-primary">${type === 'perfil' ? 'Salvar alterações' : type === 'cadastro' ? 'Criar conta' : 'Publicar'} ↗</button></div></form></div>`);
}

export function notFoundView(state) { return shell(state, 'Página em <em>construção.</em>', `<div class="empty-state card empty-state-large"><span class="empty-icon">◌</span><p class="eyebrow">Protótipo Cypher</p><h2>Esta tela está reservada para a próxima etapa.</h2><p>A navegação está funcionando, mas esta ação ainda não possui backend nem persistência.</p>${button('Voltar ao início', state.mode === 'user' ? '/dashboard' : '/explorar', 'button-primary')}</div>`); }
